name: Run Unit Test on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkar ut koden från ditt repo
      - uses: actions/checkout@v3

      # Sätter upp .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100

      # Återställer beroenden
      - name: Restore Dependencies
        run: dotnet restore

      # Kör tester
      - name: Run Unit Tests
        run: dotnet test
